services:
  sensor-data-collector:
    image: sensor-data-collector:1.0.0
    container_name: sensor-data-collector
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - sensor-data-network
    volumes:
      - .env:/app/.env
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      sensor-data-db:
        condition: service_healthy

  sensor-data-db:
    image: sensor-data-db:1.0.0
    container_name: sensor-data-db
    volumes:
      - sensor_data_db:/var/lib/postgresql/data
    build:
      context: ./db
      dockerfile: Dockerfile
      args:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - sensor-data-network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "if [ -f /tmp/db_initialized ]; then pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}; else exit 1; fi"]
      interval: 10s
      timeout: 5s
      retries: 5

  sensor-data-db-dev:
    image: postgres:16.3-alpine3.20
    container_name: sensor-data-db-dev
    volumes:
      - sensor_data_db_dev:/var/lib/postgresql/data
    networks:
      - sensor-data-network
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sensor_data_db:
  sensor_data_db_dev:

networks:
  sensor-data-network:
    driver: bridge

