// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: ambient_station_data_queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAmbientStationData = `-- name: InsertAmbientStationData :exec
INSERT INTO ambient_station_data
    (
        id, 
        "time", 
        "date", 
        timezone, 
        date_utc, 
        inside_temp_f, 
        inside_feels_like_temp_f, 
        outside_temp_f, 
        outside_feels_like_temp_f, 
        inside_humidity, 
        outside_humidity, 
        inside_dew_point, 
        outside_dew_point, 
        baro_relative, 
        baro_absolute, 
        wind_direction, 
        wind_speed_mph, 
        wind_speed_gust_mph, 
        max_daily_gust, 
        hourly_rain_inches, 
        event_rain_inches, 
        daily_rain_inches, 
        weekly_rain_inches, 
        monthly_rain_inches, 
        total_rain_inches, 
        last_rain, 
        uv_index, 
        solar_radiation, 
        outside_batt_status, 
        batt_co2, 
        sensor_id
    )
VALUES 
(
    DEFAULT, 
    $1, 
    $2, 
    $3, 
    $4, 
    $5, 
    $6, 
    $7, 
    $8, 
    $9, 
    $10, 
    $11, 
    $12, 
    $13, 
    $14, 
    $15, 
    $16, 
    $17, 
    $18, 
    $19, 
    $20, 
    $21, 
    $22, 
    $23, 
    $24, 
    $25, 
    $26, 
    $27, 
    $28, 
    $29,
    $30
)
`

type InsertAmbientStationDataParams struct {
	Time                  pgtype.Timestamptz `json:"time"`
	Date                  *string            `json:"date"`
	Timezone              *string            `json:"timezone"`
	DateUtc               *int32             `json:"date_utc"`
	InsideTempF           *float32           `json:"inside_temp_f"`
	InsideFeelsLikeTempF  *float32           `json:"inside_feels_like_temp_f"`
	OutsideTempF          *float32           `json:"outside_temp_f"`
	OutsideFeelsLikeTempF *float32           `json:"outside_feels_like_temp_f"`
	InsideHumidity        *int32             `json:"inside_humidity"`
	OutsideHumidity       *int32             `json:"outside_humidity"`
	InsideDewPoint        *float32           `json:"inside_dew_point"`
	OutsideDewPoint       *float32           `json:"outside_dew_point"`
	BaroRelative          *float32           `json:"baro_relative"`
	BaroAbsolute          *float32           `json:"baro_absolute"`
	WindDirection         *int32             `json:"wind_direction"`
	WindSpeedMph          *float32           `json:"wind_speed_mph"`
	WindSpeedGustMph      *float32           `json:"wind_speed_gust_mph"`
	MaxDailyGust          *float32           `json:"max_daily_gust"`
	HourlyRainInches      *float32           `json:"hourly_rain_inches"`
	EventRainInches       *float32           `json:"event_rain_inches"`
	DailyRainInches       *float32           `json:"daily_rain_inches"`
	WeeklyRainInches      *float32           `json:"weekly_rain_inches"`
	MonthlyRainInches     *float32           `json:"monthly_rain_inches"`
	TotalRainInches       *float32           `json:"total_rain_inches"`
	LastRain              *string            `json:"last_rain"`
	UvIndex               *float32           `json:"uv_index"`
	SolarRadiation        *float32           `json:"solar_radiation"`
	OutsideBattStatus     *int32             `json:"outside_batt_status"`
	BattCo2               *int32             `json:"batt_co2"`
	SensorID              *int64             `json:"sensor_id"`
}

func (q *Queries) InsertAmbientStationData(ctx context.Context, arg InsertAmbientStationDataParams) error {
	_, err := q.db.Exec(ctx, insertAmbientStationData,
		arg.Time,
		arg.Date,
		arg.Timezone,
		arg.DateUtc,
		arg.InsideTempF,
		arg.InsideFeelsLikeTempF,
		arg.OutsideTempF,
		arg.OutsideFeelsLikeTempF,
		arg.InsideHumidity,
		arg.OutsideHumidity,
		arg.InsideDewPoint,
		arg.OutsideDewPoint,
		arg.BaroRelative,
		arg.BaroAbsolute,
		arg.WindDirection,
		arg.WindSpeedMph,
		arg.WindSpeedGustMph,
		arg.MaxDailyGust,
		arg.HourlyRainInches,
		arg.EventRainInches,
		arg.DailyRainInches,
		arg.WeeklyRainInches,
		arg.MonthlyRainInches,
		arg.TotalRainInches,
		arg.LastRain,
		arg.UvIndex,
		arg.SolarRadiation,
		arg.OutsideBattStatus,
		arg.BattCo2,
		arg.SensorID,
	)
	return err
}
