// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: aqara_temp_sensors_unique.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAqaraUniqueData = `-- name: InsertAqaraUniqueData :exec
INSERT INTO aqara_temp_sensors_unique
    (
        id,
        timestamp,
        link_quality,
        batt_percentage,
        power_outage_count,
        device_id,
        device_type_id
    )
VALUES
    (
        DEFAULT,
        $1,
        $2,
        $3,
        $4,
        $5,
        $6
    )
`

type InsertAqaraUniqueDataParams struct {
	Timestamp        pgtype.Timestamptz `json:"timestamp"`
	LinkQuality      *float32           `json:"link_quality"`
	BattPercentage   *float32           `json:"batt_percentage"`
	PowerOutageCount *int32             `json:"power_outage_count"`
	DeviceID         *int32             `json:"device_id"`
	DeviceTypeID     *int32             `json:"device_type_id"`
}

func (q *Queries) InsertAqaraUniqueData(ctx context.Context, arg InsertAqaraUniqueDataParams) error {
	_, err := q.db.Exec(ctx, insertAqaraUniqueData,
		arg.Timestamp,
		arg.LinkQuality,
		arg.BattPercentage,
		arg.PowerOutageCount,
		arg.DeviceID,
		arg.DeviceTypeID,
	)
	return err
}
