// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: avtech_data_queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertAvtechData = `-- name: InsertAvtechData :exec
INSERT INTO avtech_data 
(
    id, 
    "time", 
    temp_f, 
    temp_f_low, 
    temp_f_high, 
    temp_c, 
    temp_c_low, 
    temp_c_high, 
    sensor_id
) 
VALUES 
(
    DEFAULT, 
    $1, 
    $2, 
    $3, 
    $4, 
    $5, 
    $6, 
    $7, 
    $8
)
`

type InsertAvtechDataParams struct {
	Time      pgtype.Timestamptz `json:"time"`
	TempF     *float32           `json:"temp_f"`
	TempFLow  *float32           `json:"temp_f_low"`
	TempFHigh *float32           `json:"temp_f_high"`
	TempC     *float32           `json:"temp_c"`
	TempCLow  *float32           `json:"temp_c_low"`
	TempCHigh *float32           `json:"temp_c_high"`
	SensorID  *int64             `json:"sensor_id"`
}

func (q *Queries) InsertAvtechData(ctx context.Context, arg InsertAvtechDataParams) error {
	_, err := q.db.Exec(ctx, insertAvtechData,
		arg.Time,
		arg.TempF,
		arg.TempFLow,
		arg.TempFHigh,
		arg.TempC,
		arg.TempCLow,
		arg.TempCHigh,
		arg.SensorID,
	)
	return err
}
