// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: mqtt_config_queries.sql

package sqlc

import (
	"context"
)

const getUniqueMqttTopics = `-- name: GetUniqueMqttTopics :many
SELECT DISTINCT mqtt_topic FROM mqtt_config
`

func (q *Queries) GetUniqueMqttTopics(ctx context.Context) ([]*string, error) {
	rows, err := q.db.Query(ctx, getUniqueMqttTopics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*string
	for rows.Next() {
		var mqtt_topic *string
		if err := rows.Scan(&mqtt_topic); err != nil {
			return nil, err
		}
		items = append(items, mqtt_topic)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
