// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: pi_sensor_data_queries.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertPiSensorData = `-- name: InsertPiSensorData :exec
INSERT INTO pi_sensor_data
(
    id,
    "time",
    temp_f,
    temp_c,
    humidity,
    sensor_location,
    sensor_id
)
VALUES
(
    DEFAULT,
    $1,
    $2,
    $3,
    $4,
    $5,
    $6
)
`

type InsertPiSensorDataParams struct {
	Time           pgtype.Timestamptz `json:"time"`
	TempF          *float32           `json:"temp_f"`
	TempC          *float32           `json:"temp_c"`
	Humidity       *float32           `json:"humidity"`
	SensorLocation *string            `json:"sensor_location"`
	SensorID       *int64             `json:"sensor_id"`
}

func (q *Queries) InsertPiSensorData(ctx context.Context, arg InsertPiSensorDataParams) error {
	_, err := q.db.Exec(ctx, insertPiSensorData,
		arg.Time,
		arg.TempF,
		arg.TempC,
		arg.Humidity,
		arg.SensorLocation,
		arg.SensorID,
	)
	return err
}
