// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"context"
)

type Querier interface {
	GetSensorIdBySensorName(ctx context.Context, sensorName string) (int64, error)
	GetSensors(ctx context.Context) ([]*Sensor, error)
	InsertAmbientStationData(ctx context.Context, arg InsertAmbientStationDataParams) error
	InsertAvtechData(ctx context.Context, arg InsertAvtechDataParams) error
	InsertPiSensorData(ctx context.Context, arg InsertPiSensorDataParams) error
}

var _ Querier = (*Queries)(nil)
