// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: device_type_ids.sql

package sqlc

import (
	"context"
)

const getDeviceTypeIDByDeviceType = `-- name: GetDeviceTypeIDByDeviceType :one
SELECT 
    device_type_id
FROM
    device_type_ids
WHERE
    device_type = $1
`

func (q *Queries) GetDeviceTypeIDByDeviceType(ctx context.Context, deviceType string) (int32, error) {
	row := q.db.QueryRow(ctx, getDeviceTypeIDByDeviceType, deviceType)
	var device_type_id int32
	err := row.Scan(&device_type_id)
	return device_type_id, err
}
