// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: shared_atmospheric_readings.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertReading = `-- name: InsertReading :exec
INSERT INTO shared_atmospheric_readings
    (
        id, 
        timestamp, 
        temp_f, 
        temp_c,
        humidity,
        absolute_pressure,
        device_type_id,
        device_id 
    )
VALUES
    (
        DEFAULT,
        $1,
        $2,
        $3,
        $4,
        $5,
        $6,
        $7
    )
`

type InsertReadingParams struct {
	Timestamp        pgtype.Timestamptz `json:"timestamp"`
	TempF            *float32           `json:"temp_f"`
	TempC            *float32           `json:"temp_c"`
	Humidity         *float32           `json:"humidity"`
	AbsolutePressure *float32           `json:"absolute_pressure"`
	DeviceTypeID     *int32             `json:"device_type_id"`
	DeviceID         *int32             `json:"device_id"`
}

func (q *Queries) InsertReading(ctx context.Context, arg InsertReadingParams) error {
	_, err := q.db.Exec(ctx, insertReading,
		arg.Timestamp,
		arg.TempF,
		arg.TempC,
		arg.Humidity,
		arg.AbsolutePressure,
		arg.DeviceTypeID,
		arg.DeviceID,
	)
	return err
}
