// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: sonoff_smart_plugs.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertSonoffSmartPlugReading = `-- name: InsertSonoffSmartPlugReading :exec
INSERT INTO
    sonoff_smart_plugs (
        id,
        timestamp,
        link_quality,
        outlet_state,
        device_id,
        device_type_id
    )
VALUES (
    DEFAULT,
    $1,
    $2,
    $3,
    $4,
    $5
)
`

type InsertSonoffSmartPlugReadingParams struct {
	Timestamp    pgtype.Timestamptz `json:"timestamp"`
	LinkQuality  *int32             `json:"link_quality"`
	OutletState  *int32             `json:"outlet_state"`
	DeviceID     *int32             `json:"device_id"`
	DeviceTypeID *int32             `json:"device_type_id"`
}

func (q *Queries) InsertSonoffSmartPlugReading(ctx context.Context, arg InsertSonoffSmartPlugReadingParams) error {
	_, err := q.db.Exec(ctx, insertSonoffSmartPlugReading,
		arg.Timestamp,
		arg.LinkQuality,
		arg.OutletState,
		arg.DeviceID,
		arg.DeviceTypeID,
	)
	return err
}
